---
include:
  - board: cosmos_lemon_wireless
    shield: peamk_r2c_left
  - board: cosmos_lemon_wireless
    shield: peamk_r2c_right vik_pmw3610
  - board: cosmos_lemon_wireless
    shield: settings_reset
